# Generated by Django 4.1.6 on 2023-07-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_content_academy_content_arena'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content_Arena',
            new_name='Academy',
        ),
        migrations.RenameModel(
            old_name='Content_Academy',
            new_name='Arena',
        ),
    ]
