# Generated by Django 4.1.6 on 2023-07-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_background_slider_delete_header_shop_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
