# Generated by Django 4.1.6 on 2023-07-11 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_slider_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.photo'),
        ),
    ]
