# Generated by Django 4.1.6 on 2023-07-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_photo_alter_slider_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='photo',
        ),
        migrations.AddField(
            model_name='slider',
            name='photo',
            field=models.ManyToManyField(to='main.photo'),
        ),
    ]
