# Generated by Django 4.1.6 on 2023-07-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_slider_photo_slider_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='background',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
